### PR TITLE
stage-react-api

### PR DESCRIPTION
**Pull request by leonid9191**
stage-react-api

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Leonid!

Great job with your diploma project! Some issues will be necessary to correct, but on the whole it looks pretty good!

First of all, please note that there is an error when complinig: https://prnt.sc/v-qmcOhJiSIV

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* https://prnt.sc/s62FtAOq3imN Background is cropped
* https://prnt.sc/mbUhUrnPPS-8 https://prnt.sc/QCeoryLB_3Wb Card layout breaks on mobile screens
* https://prnt.sc/tJMNy59VxyEa form doesn't match the design on mobile screens. The same on tablets: https://prnt.sc/RwCocznX6Pjt
* There should be no "Search results" title on "saved-articles" page
* https://prnt.sc/JsvN_Brh-Ghx In the modile footer, icons should be horizontally aligned with "Home" link and links should have some space at the top

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* saved-articles page scrolls on 481 - 572
* https://prnt.sc/ShqOn03d3eF7 tablet screens should have 3 cards in a row

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Links in footer should be working

- [x]  Classes are named according to BEM specifications.

* https://prnt.sc/7WksToLfR5qP Modifiers are used incorrectly, they are not needed here. These should be just elements
* https://prnt.sc/Crzs5RDVsNWz duplicated class name


- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* `header` is missing. The page should have a proper semantic structure with header, main and footer. Main should contain all unique content sections of the page.
* `new-card-list__title` should be a heading
* news cards list should be a list `<ul>`, or/and the card needs to be `<article>`
* `about-me__description` isn't a paragraph, please don't use br to separate paragraphs. This should be a text with several paragraphs inside

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover effect on a card bookmark from the mockup: https://skr.sh/sH0y9Tkgpph

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 46

**Comment by ImaliaNsk** [comment]
Thanks for the corrections! They look good, but some further refactoring will be necessary.

Please note that an error is still there: https://prnt.sc/v-qmcOhJiSIV. It's necessary to rename the file.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.

* On 320 the cards are too narrow, and not centered

- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* "Home" page scrolls on 320 - 327
* The list of cards has a default padding, and the content isn't centered because of it
* https://prnt.sc/CuEB8bYH54Cs The content isn't centered, the cards are too narrow, and the icon is cropped. Please check on all resolutions

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* "Practicum" link isn't working

- [x]  Classes are named according to BEM specifications.

* `search-form__form_input` shouldn't be a modifier, BEM entity can't contain only a modifier. The input needs an element class.

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.

* `main` shouldn't contain header. It should contain only main content of the page, excluding header and footer. The main project html structure should be header main footer.
* `<article>` can't be a direct child of `<ul>`

- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.

* Hover effect on a card bookmark from the mockup: https://skr.sh/sH0y9Tkgpph

- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* Please correct for `popup__title`

- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 48

**Comment by ImaliaNsk** [comment]
Please note that an error is still there: https://prnt.sc/v-qmcOhJiSIV. It's necessary to rename the file. Note that the project can't be accepted with this error, so please fix it next time.

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The cards are too narrow on interemediate resolutions: https://prnt.sc/_t5mTPpcamj8 https://prnt.sc/gDlRE0v9Cva5, the layout looks broken. Also note how the images are displayed.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.

* Links should be opened in new tabs. Sorry for not indicating this before.

- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

https://prnt.sc/v-qmcOhJiSIV

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* Please correct for `popup__title`

- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 79

**Comment by leonid9191** [comment]
I'm sorry, but I don't see this error in my project. [https://prnt.sc/v-qmcOhJiSIV](url)
Also I use npm package for image optimization.

**Comment by leonid9191** [comment]
image

**Comment by ImaliaNsk** [comment]
Congratulations! The project is accepted, I wish you good luck on the next stage!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* The cards are too narrow on interemediate resolutions: https://prnt.sc/_t5mTPpcamj8 https://prnt.sc/gDlRE0v9Cva5, the layout looks broken. Also note how the images are displayed.

- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.  
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [ ]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.

### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.

* Please correct for `popup__title`

- [x]  Images have an `alt` attribute containing appropriate values.
- [ ]  Raster and vector images have been optimized.

## Number of points: 84

**Pull request merged**
